import { DevtoolsProvider } from "@providers/devtools";
import { GitHubBanner, Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import { notificationProvider, RefineSnackbarProvider } from "@refinedev/mui";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { AppIcon } from "@components/app-icon";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProvider } from "@providers/auth-provider";
import {
  dataProviders,
  PROVIDER_NAME_PET_CLINIC,
} from "@providers/data-provider";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    (<html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <ColorModeContextProvider defaultMode={defaultMode}>
              <RefineSnackbarProvider>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    dataProvider={dataProviders}
                    notificationProvider={notificationProvider}
                    authProvider={authProvider}
                    resources={[{
                      name: "petclinic",
                      meta: {
                        canDelete: false,
                        label: "Pet clinic",
                      },
                    }, {
                      name: "vets",
                      list: "/petclinic/vets",
                      create: "/petclinic/vets/create",
                      edit: "/petclinic/vets/edit/:id",
                      show: "/petclinic/vets/show/:id",
                      meta: {
                        label: "Vets",
                        dataProviderName: PROVIDER_NAME_PET_CLINIC,
                        parent: "petclinic",
                      },
                    }, {
                      name: "owners",
                      list: "/petclinic/owners",
                      create: "/petclinic/owners/create",
                      edit: "/petclinic/owners/edit/:id",
                      show: "/petclinic/owners/show/:id",
                      meta: {
                        label: "Owners",
                        dataProviderName: PROVIDER_NAME_PET_CLINIC,
                        parent: "petclinic",
                      },
                    }, {
                      name: "master-data",
                      meta: {
                        canDelete: false,
                        label: "Master Data",
                        parent: "petclinic",
                      },
                    }, {
                      name: "specialties",
                      list: "/petclinic/specialties",
                      create: "/petclinic/specialties/create",
                      edit: "/petclinic/specialties/edit/:id",
                      show: "/petclinic/specialties/show/:id",
                      meta: {
                        canDelete: true,
                        dataProviderName: PROVIDER_NAME_PET_CLINIC,
                        parent: "master-data",
                      },
                    }, {
                      name: "pet-types",
                      list: "/petclinic/pet-types",
                      create: "/petclinic/pet-types/create",
                      edit: "/petclinic/pet-types/edit/:id",
                      show: "/petclinic/pet-types/show/:id",
                      meta: {
                        label: "PetTypes",
                        dataProviderName: PROVIDER_NAME_PET_CLINIC,
                        parent: "master-data",
                      },
                    }, {
                      name: "demo",
                      meta: {
                        canDelete: true,
                      },
                    }, {
                      name: "blog_posts",
                      list: "/demo/blog-posts",
                      create: "/demo/blog-posts/create",
                      edit: "/demo/blog-posts/edit/:id",
                      show: "/demo/blog-posts/show/:id",
                      meta: {
                        canDelete: true,
                        parent: "demo",
                      },
                    }, {
                      name: "categories",
                      list: "/demo/categories",
                      create: "/demo/categories/create",
                      edit: "/demo/categories/edit/:id",
                      show: "/demo/categories/show/:id",
                      meta: {
                        canDelete: true,
                        parent: "demo",
                      },
                    }]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "bnIDBt-1Lty3v-DIgvyH",
                      title: { text: "Refine Project", icon: <AppIcon /> },
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </RefineSnackbarProvider>
            </ColorModeContextProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>)
  );
}
